### ISSUE TITLE
数値目標設定

### ISSUE THREAD

**Issue by sakastudio** [moorestech/ProjectManagement#3]

**Comment by RyotaTokuda** [comment]
まずは、Steam、ディスコード、ツイッター？

**Comment by sakastudio** [comment]
数値目標

## 初月売上
やんちゃ　500万 Steamのトップインディーゲームと同じ水準
ベース　300万 トップ自動化工業ゲームと同じ水準
下限　10万 標準的な自動化工業ゲームと同じ水準、インディーゲームとしては大成功
最低　5万 インディーゲームとしてはまずまずな成功


## ウィッシュリスト

80万

ウイッシュリストから購入につながる率は15%程度なので、単純に考えれば目標達成には2000万必要になる。しかしそれは現実的じゃないし、数百万本売れてるゲームももとからそれくらい知名度があったわけじゃない。そのようなゲームは初日に10万本程度売れ、その後、Steam売上上位へのランクインや口コミによって初月数百万セールスにつながっている。
つまり、目標達成には初日から数日で10万本から数十万本の売上が必要になり、他のゲームを参考にしても初日ではそれくらい売れている。そのため、他ゲーの参考と初日に数十万本売るという観点から、80万ウイッシュリストを目標にした。

## Steamフォロワー
10万

Steamフォロワーは10万を目指すのではなく、「ウィッシュリストの質」の指標とする。過去の記事とデータから、ウィッシュリスト:フォロワーが8:1〜10:1程度であれば、「ウィッシュリストの質」が高く、コンバージョン率が良くなる（ウィッシュリスト登録のうち買ってくれる人が多い）傾向にある。これが10:1〜15:1になると、「ウィッシュリストの質」が下がり、コンバージョン率が下がる傾向にある。そのため、ウィッシュリストへの登録は促すが、フォロワーの登録は促さず、現在のウィッシュリストの質がどの程度かを判断する材料にする。
この場合、10万フォロワーは目標ウィッシュリストの1/8となり、質の高いウィッシュリストを目指すということになる。

参考
https://indiegamesjp.dev/?p=2975
https://newsletter.gamediscover.co/p/why-your-steam-follower-to-wishlist


## Discord
10万

こちらは上のフォロワーやウィッシュリストほど調べている訳では無いが、Discordコミュニティの構築をきちんと行っているゲームはこの程度の参加者がいるので、これを目標とした。これは強い目標ではないが、一つの指標として参考にするためのものである。


## Twitter
目標なし

インディーゲームでTwitterのフォロワーはあまり影響しないため、積極的な目標設定はしない
